AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31

Parameters:
  EnvType:
    Type: String
    Default: dev
    AllowedValues: [prod, dev]
  AWSAccountId:
    Type: String
    Default: "240435918890"
  QuickSightUserArn:
    Type: String
    Default: "arn:aws:quicksight:us-east-1:240435918890:user/default/diego-dev"
  AllowedDomain:
    Type: String
    Default: "https://d19kpussj440vd.cloudfront.net"  # Cambia a HTTPS

Resources:
  GenerateEmbedUrlFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: generateEmbedUrl/
      Handler: index.handler
      Runtime: nodejs18.x
      Environment:
        Variables:
          AWS_ACCOUNT_ID: !Ref AWSAccountId
          QUICKSIGHT_USER_ARN: !Ref QuickSightUserArn
          ALLOWED_DOMAIN: !Ref AllowedDomain
      Policies:
        - Version: "2012-10-17"
          Statement:
            - Effect: Allow
              Action: 
                - quicksight:GenerateEmbedUrlForRegisteredUser
                - quicksight:DescribeDashboard
              Resource: "*"
      Events:
        GetEmbedUrl:
          Type: Api
          Properties:
            RestApiId: !Ref EmbedUrlApi
            Path: /getEmbedUrl
            Method: GET

  EmbedUrlApi:
    Type: AWS::Serverless::Api
    Properties:
      StageName: !Ref EnvType
      Cors:
        AllowMethods: "'GET'"
        AllowOrigin: !Sub "'${AllowedDomain}'"
        AllowHeaders: "'Content-Type,X-Amz-Date,Authorization,X-Api-Key'"