version = 0.1
[default.deploy.parameters]
stack_name = "ingesta-microservices-saas"
resolve_s3= true
s3_prefix = "ingesta-microservices-saas"
region = "us-east-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
disable_rollback = true
image_repositories = []
